bookshop/urls.py
from django.urls import path

from bookshop.views import HomePageView, PublisherView, StoreListView, StoreDetialView, StoreCreateView, \
    AuthorCreateView, AuthorListView, AuthorDetialView, BookListView, BookCreateView, BookDetialView, BookUpdateView

app_name = "bookshop"
urlpatterns = [
    path("", HomePageView.as_view(), name="home-page"),
    path("publisher/", PublisherView.as_view(), name="publisher-page"),
    path("stores/", StoreListView.as_view(), name="store-list"),
    path("stores/create", StoreCreateView.as_view(), name="store-create"),
    path("stores/<int:pk>", StoreDetialView.as_view(), name="store-detail"),
    path("authors/create", AuthorCreateView.as_view(), name="author-create"),
    path("authors/", AuthorListView.as_view(), name="author-list"),
    path("authors/<int:pk>", AuthorDetialView.as_view(), name="author-detail"),
    path("books/", BookListView.as_view(), name="book-list"),
    path("books/create", BookCreateView.as_view(), name="book-create"),
    path("books/<int:pk>", BookDetialView.as_view(), name="book-detail"),
    path("books/update/<int:pk>", BookUpdateView.as_view(), name="book-update")
]

courses/urls.py
from django.urls import path

from courses.views import home_page, teacher_detail, speciality_detail, speciality_create

app_name = "courses"
urlpatterns = [
    path('', home_page, name='home-page'),
    path('specility/create', speciality_create, name='speciality-create'),
    path('teacher/<id>', teacher_detail, name='teacher-detail'),
    path('specility/<id>', speciality_detail, name='speciality-detail'),
]

university/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls')),
    path('bookshop/', include('bookshop.urls')),
    path('', TemplateView.as_view(template_name='home.html'))
]

bookshop/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class AbtractBaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Author(AbstractUser):
    GENDER_CHOICE = [
        ('m', 'Male'),
        ('f', 'Female'),
    ]

    age = models.IntegerField(null=True)
    address = models.TextField(null=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICE, null=True)

    class Meta:
        verbose_name_plural = "Authors"

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('bookshop:author-list', kwargs={"pk": self.id})


class Publisher(AbtractBaseModel):
    name = models.CharField(max_length=86)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Book(AbtractBaseModel):
    name = models.CharField(max_length=56)
    pages = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    rating = models.FloatField()
    authors = models.ManyToManyField(Author, related_name="books")
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE, related_name="books")
    pubdate = models.DateField()

    def __str__(self):
        return self.name


class Store(models.Model):
    name = models.CharField(max_length=300)
    books = models.ManyToManyField(Book, related_name="stores")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('bookshop:store-detail', kwargs={"pk": self.id})

bookshop/forms.py
from django import forms
from django.forms import ModelForm

from bookshop.models import Publisher, Store, Author, Book


class PublisherCreateForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = ["name", "is_active"]


class StoreCreateForm(ModelForm):
    class Meta:
        model = Store
        fields = ["name", "books"]


class AuthorCreateForm(ModelForm):
    class Meta:
        model = Author
        fields = ["username"]

class BookCreateForm(ModelForm):
    class Meta:
        model = Book
        fields = ["name", "rating", "price"]

class BookUpdateForm(ModelForm):
    class Meta:
        model = Book
        fields = ["name"]

bookshop/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from bookshop.forms import PublisherCreateForm, StoreCreateForm, AuthorCreateForm, BookCreateForm, BookUpdateForm
from bookshop.models import Publisher, Store, Author, Book

"""
function based views 
class based views 
    View
    generic
"""


class HomePageView(View):
    def get(self, request):
        return render(request, "bookshop/home.html")


class PublisherView(View):
    def get(self, request):
        publishers = Publisher.objects.all().order_by("-created_at")[:5]
        form = PublisherCreateForm()
        context = {
            "publishers": publishers,
            "form": form
        }
        return render(request, "bookshop/publisher.html", context=context)

    def post(self, request):
        publishers = Publisher.objects.all().order_by("-created_at")[:5]
        form = PublisherCreateForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("bookshop:publisher-page")
        else:
            return render(request, "bookshop/publisher.html", context={
                "publishers": publishers,
                "form": form
            })

class StoreListView(ListView):
    model = Store
    context_object_name = "stores"
    template_name = "bookshop/store_list.html"

class StoreDetialView(DetailView):
    model= Store
    template_name = "bookshop/store_detail.html"
    context_object_name = "store"

class StoreCreateView(CreateView):
    model = Store
    form = StoreCreateForm
    fields = ["name", "books"]
    template_name = "bookshop/store_create.html"

class AuthorListView(ListView):
    model = Author
    context_object_name = "authors"
    template_name = "bookshop/author_list.html"

class AuthorDetialView(DetailView):
    model= Author
    template_name = "bookshop/author_detail.html"
    context_object_name = "author"

class AuthorCreateView(CreateView):
    model = Author
    form=AuthorCreateForm
    fields = ["username", "first_name", "last_name", "age"]
    template_name = "bookshop/author_create.html"

class BookListView(ListView):
    model = Book
    context_object_name = "books"
    template_name = "bookshop/book_list.html"

class BookDetialView(DetailView):
    model= Book
    template_name = "bookshop/book_detail.html"
    context_object_name = "book"

class BookCreateView(CreateView):
    model = Book
    form = BookCreateForm
    fields = ["name", "rating", "price"]
    template_name = "bookshop/book_create.html"

class BookUpdateView(UpdateView):
    model = Book
    form = BookUpdateForm
    fields = ["name", "rating", "price"]
    template_name = "bookshop/book_update.html"

templates/bookshop/author_create.html
{% extends 'bookshop/base.html' %}
{% block title %}author Detail{% endblock %}
{% block body %}
    <h1>Author Create Page</h1>
    <form method="post" action="{% url 'bookshop:author-create' %}">
        {{ form.as_div }}
        {% csrf_token %}
        <button type="submit">Create Store</button>
    </form>
{% endblock %}

templates/bookshop/author_detail.html
    {% extends 'bookshop/base.html' %}
    {% block title %}Author Detail{% endblock %}
    {% block body %}
        <h1>Author Detail Page</h1>
        <h3>{{ author.username }}  {{ author.is_superuser }}  {{ author.is_active }}</h3>
    {% endblock %}

templates/bookshop/author_list.html
{% extends "bookshop/base.html" %}
{% block title %}Author List{% endblock %}
{% block body %}
    <h1>Author List Page</h1>
    <a href="{% url 'bookshop:author-create' %}"><button>Create Author</button></a> <br>
    {% for author in authors %}
        <a href="{% url 'bookshop:author-detail' author.id %}"> {{ author.username }} </a><br>
    {% endfor %}
{% endblock %}

templates/bookshop/base.html
<html>
<head>
    <title>
        {% block title %}
        Base html
        {% endblock %}
    </title>
</head>
<body>
{% block body %}

{% endblock %}

</body>


</html>

templates/bookshop/book_create.html
{% extends 'bookshop/base.html' %}
{% block title %}Book Detail{% endblock %}
{% block body %}
    <h1>Book Create Page</h1>
    <form method="post" action="{% url 'bookshop:book-create' %}">
        {{ form.as_div }}
        {% csrf_token %}
        <button type="submit">Create Book</button>
    </form>
{% endblock %}

templates/bookshop/book_detail.html
    {% extends 'bookshop/base.html' %}
    {% block title %}Book Detail{% endblock %}
    {% block body %}
        <h1>Book Detail Page</h1>
        <h3> name:{{ book.name }} <br> rating: {{ book.rating }}<br>  publisher: {{ book.publisher }}<br></h3>
    {% endblock %}

templates/bookshop/book_list.html
{% extends "bookshop/base.html" %}
{% block title %}Book List{% endblock %}
{% block body %}
    <h1>Book List Page</h1>
    <a href="{% url 'bookshop:book-create' %}"><button>Create Book</button></a> <br>
    {% for book in books %}
        <a href="{% url 'bookshop:book-detail' book.id %}">name: {{ book.name }}    publisher: {{ book.publisher }} </a><br>
    {% endfor %}
{% endblock %}

templates/bookshop/book_update.html
{% extends 'bookshop/base.html' %}
{% block title %}Book Update{% endblock %}
{% block body %}
    <h1>Book Update Page</h1>
    <form method="post" action="{% url 'bookshop:book-update' %}">
        {{ form.as_div }}
        {% csrf_token %}
        <button type="submit">Create Book</button>
    </form>
{% endblock %}

templates/bookshop/home.html
{% extends 'bookshop/base.html' %}
{% block title %} Bookshop Home Page {% endblock %}
{% block body %}
    <h1>Book Shop Page</h1>
    <a href="{% url 'bookshop:publisher-page' %}">publishers</a><br><br>
    <a href="{% url 'bookshop:store-list' %}"> stores</a><br><br>
    <a href="{% url 'bookshop:author-list' %}"> authors </a><br><br>
    <a href="{% url 'bookshop:book-list' %}">books</a><br><br>
{% endblock %}

templates/bookshop/publisher.html
{% extends 'bookshop/base.html' %}
{% block title %} Publisher {% endblock %}

{% block body %}
    <h3>   Publisher Create Page </h3>
    <form action="{% url 'bookshop:publisher-page' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
    </form>
    <br>
    <hr>
    {% for publisher in publishers %}
        {{ publisher.name }} {{ publisher.created_at }} {{ publisher.is_active }} <br>
    {% endfor %}
{% endblock %}

templates/bookshop/store.html
{% extends 'bookshop/base.html' %}
{% block title %} Store {% endblock %}

{% block body %}
    <h3>   store Create Page </h3>
    <form action="{% url 'bookshop:store-page' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
    </form>
    <br>
    <hr>
    {% for st in store %}
        {{ st.name }} {{ st.books }} <br>
    {% endfor %}
{% endblock %}

templates/bookshop/store_create.html
{% extends 'bookshop/base.html' %}
{% block title %}Store Detail{% endblock %}
{% block body %}
    <h1>Store Create Page</h1>
    <form method="post" action="{% url 'bookshop:store-create' %}">
        {{ form.as_div }}
        {% csrf_token %}
        <button type="submit">Create Store</button>
    </form>
{% endblock %}

templates/bookshop/store_detail.html
    {% extends 'bookshop/base.html' %}
    {% block title %}Store Detail{% endblock %}
    {% block body %}
        <h1>Store Detail Page</h1>
        <h3>{{ store.name }}</h3>
        {% for book in store.books.all %}
            {{ book.name }} {{ book.rating }} {{ book.price }}  <br>
        {% endfor %}
    {% endblock %}

templates/bookshop/store_list.html
{% extends "bookshop/base.html" %}
{% block title %}Store List{% endblock %}
{% block body %}
    <h1>Store List Page</h1>
    <a href="{% url 'bookshop:store-create' %}"><button>Create Store</button></a> <br>
    {% for store in stores %}
        <a href="{% url 'bookshop:store-detail' store.id %}"> {{ store.name }} </a><br>
    {% endfor %}
{% endblock %}