courses/urls.py
from django.urls import path

from courses.views import home_page, teacher_detail, speciality_detail, speciality_create

app_name = "courses"
urlpatterns = [
    path('', home_page, name='home-page'),
    path('specility/create', speciality_create, name='speciality-create'),
    path('teacher/<id>', teacher_detail, name='teacher-detail'),
    path('specility/<id>', speciality_detail, name='speciality-detail'),
]

university/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls')),
    path('bookshop/', include('bookshop.urls')),
    path('', TemplateView.as_view(template_name='home.html'))
]

courses/models.py
import datetime
from uuid import uuid4

from django.db import models
from django.utils.text import slugify


class AbtractModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Subject(AbtractModel):
    name = models.CharField(max_length=28, )
    teacher = models.ForeignKey('Teacher', on_delete=models.CASCADE, related_name="subjects")
    speciality = models.ManyToManyField('Speciality', related_name="subjects")

    class Meta:
        verbose_name = "Subject"
        verbose_name_plural = "Subjects"
        db_table = "subject"

    def __str__(self):
        return f"{self.name}"


class Teacher(AbtractModel):
    Degree = [
        ("master", "Master"),
        ("bachelor", "Bachelor"),
        ("academic", "Academic"),
        ("drscience", "DrScience"),
        ("phs", "PhD"),
    ]

    first_name = models.CharField(max_length=28)
    last_name = models.CharField(max_length=28)
    degree = models.CharField(max_length=9, choices=Degree)
    age = models.IntegerField()
    email = models.EmailField(unique=True)

    class Meta:
        verbose_name = "Teacher"
        verbose_name_plural = "Teachers"
        db_table = "teacher"

    def __str__(self):
        return "{0}{1}".format(self.first_name, self.last_name)


class Speciality(AbtractModel):
    name = models.CharField(max_length=28)
    code = models.UUIDField(default=uuid4)
    is_active = models.BooleanField(default=False)
    start_date = models.DateField()
    slug = models.SlugField(unique=True, blank=True)

    class Meta:
        verbose_name = "Speciliality"
        verbose_name_plural = "Specilialities"
        db_table = "speciality"

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify("-".join([self.start_date, self.name]))
        super().save(force_insert, force_update, using, update_fields)

    def __str__(self):
        return f"{self.name}"

courses/forms.py
from django import forms

from courses.models import Speciality


class SpecialityForm(forms.Form):
    name = forms.CharField(max_length=36)
    date = forms.DateField()
    is_active = forms.BooleanField()

    def save(self):
        name = self.cleaned_data["name"]
        date = str(self.cleaned_data["date"])
        is_active = self.cleaned_data["is_active"]
        speciality = Speciality.objects.create(name=name, start_date=date, is_active=is_active)
        return speciality

courses/views.py
from django.shortcuts import render, redirect

from courses.forms import SpecialityForm
from courses.models import Subject, Speciality, Teacher


def home_page(request):
    subjects = Subject.objects.all().order_by("-created_at")[:5]
    specialities = Speciality.objects.all().order_by("-created_at")[:5]
    teachers = Teacher.objects.all().order_by("-created_at")[:5]
    context = {
        "subjects": subjects,
        "specialities": specialities,
        "teachers": teachers
    }
    return render(request, 'courses/home.html', context=context)


def teacher_detail(request, id):
    teacher = Teacher.objects.get(id=id)
    context = {
        "teacher": teacher
    }
    return render(request, 'courses/teacher_detail.html', context=context)


def speciality_detail(request, id):
    speciality = Speciality.objects.get(id=id)
    context = {
        "speciality": speciality
    }
    return render(request, 'courses/speciality_detial.html', context=context)


def speciality_create(request):
    form = SpecialityForm
    if request.method == "POST":
        form = SpecialityForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('courses:home-page')
        else:
            return render(request, "courses/speciality_create.html", context={"form": form})


    else:
        return render(request, "courses/speciality_create.html", context={"form": form})

templates/courses/home.html
{% extends 'courses/base.html' %}
{% block title %} Home Page {% endblock %}
{% block body %}
    <h1>Teachers</h1> <a href=""> Create New Teacher</a>
    {% for teacher in teachers %}
        <a href="{% url 'courses:teacher-detail' teacher.id %}">{{ teacher.first_name }}</a> <br>
    {% endfor %}
    <h1>Specialities</h1><br><a type="button" href="{% url 'courses:speciality-create' %}" ><button>create new speciality</button></a><br> <br>
    {% for speciality in specialities %}
        <a href="{% url 'courses:speciality-detail' speciality.id %}">{{ speciality.name }}</a> <br>
    {% endfor %}
    <h1>Subjects</h1>
    {% for subject in subjects %}
        <a href="">{{ subject.name }}</a> <br>
    {% endfor %}

{% endblock %}

templates/courses/speciality_create.html
{% extends 'courses/base.html' %}
{% block title %} Specialiity Create Page {% endblock %}
{% block body %}
    <h1>Speciality Create Page</h1>
    <form action="{% url 'courses:speciality-create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Submit</button>
    </form>
{% endblock %}

templates/courses/speciality_detial.html
{%  extends 'courses/base.html' %}
{% block title %} Speciality Detail Page {% endblock %}
{% block body %}
    <h1>Speciality Detial Page </h1>
    <p><b>Specility Name </b> {{ speciality.name }} </p>
    <p><b>Specility Code </b> {{ speciality.code }} </p>
    <p><b>Specility Created Date </b> {{ speciality.created_at }} </p>
    <p><b>Specility Slug </b> {{ speciality.slug }} </p>

{% endblock %}

templates/courses/teacher_create.html
{% extends 'courses/base.html' %}
{% block title %} Teacher Create Page {% endblock %}
{% block body %}
    <h1>Teacher Create Page</h1>
    <form action="{% url 'courses:teacher-create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Submit</button>
    </form>
{% endblock %}

templates/courses/teacher_detail.html
{% extends 'courses/base.html' %}
{% block title %} Teacher Detail Page {% endblock %}
{% block body %}
    <h1>Teacher Info</h1>
    <p> <b>Teacher First Name: </b>{{ teacher.first_name }}</p>
    <p> <b>Teacher Last Name: </b>{{ teacher.last_name }}</p>
    <p> <b>Teacher Degree: </b>{{ teacher.degree }}</p>
    <p> <b>Teacher Age: </b>{{ teacher.age }}</p>


{% endblock %}